# Generated by Django 5.1.1 on 2024-09-21 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='income',
            name='expenses',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='income',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
